# Generated by Django 4.2.11 on 2024-10-02 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_product_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(limit_choices_to={'is_restaurant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='restaurant',
            field=models.ForeignKey(limit_choices_to={'is_restaurant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='restaurant',
            field=models.ForeignKey(limit_choices_to={'is_restaurant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_package_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
