export const LOADING_START = "LOADING_START";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const CONTINUOUS_USER_AUTH_SUCCESS = "CONTINUOUS_USER_AUTH_SUCCESS";
export const CONTINUOUS_USER_AUTH_FAILED = "CONTINUOUS_USER_AUTH_FAILED";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const EMAIL_CHANGE_REQUEST_SUCCESS = "EMAIL_CHANGE_REQUEST_SUCCESS";
export const EMAIL_CHANGE_REQUEST_FAILED = "EMAIL_CHANGE_REQUEST_FAILED";

export const PASSWORD_CHANGE_REQUEST_SUCCESS = "PASSWORD_CHANGE_REQUEST_SUCCESS";
export const PASSWORD_CHANGE_REQUEST_FAILED = "PASSWORD_CHANGE_REQUEST_FAILED";

export const PASSWORD_CHANGE_CONFIRM_REQUEST_SUCCESS = "PASSWORD_CHANGE_CONFIRM_REQUEST_SUCCESS";
export const PASSWORD_CHANGE_CONFIRM_REQUEST_FAILED = "PASSWORD_CHANGE_CONFIRM_REQUEST_FAILED";

export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_REMOVE = "PRODUCT_REMOVE";
export const SET_PRODUCT_COUNT = "SET_PRODUCT_COUNT";